#!/usr/bin/env python3
"""
gen_iff.py  -  Stage E: generate the IFF interrogation stream for scenario3
============================================================================
The IFF interrogator pings each epoch; friendly aircraft (a fixed subset of
the 100 targets, with working transponders) reply with a coded friend response
tagged to their position. Non-friends never reply. Replies drop out
occasionally (transponder blanking / antenna geometry) so labeling must be
robust, not one-shot.

IFF does NOT refine track kinematics - it is a LABEL. So the stream is just
friend-reply positions per epoch: [x,y,z] each. The board correlates them to
tracks (track_mgr) and marks matched tracks FRIEND.

Outputs:
  iff3.h          C header: s3_iff_ndet[NEPOCH], s3_iff_det[...] (x,y,z per reply)
  friend_mask.npy bool[100] - which target indices are friends (for verify.py)
"""
import numpy as np

TRUTH = "truth_s3.npy"
FRIEND_FRAC = 0.42        # ~42% of targets are friendly
P_REPLY     = 0.90        # per-epoch probability a friend actually replies
IFF_POS_SIG = 40.0        # IFF position tag noise [m] (coarser than radar)
SEED        = 11

def main():
    t = np.load(TRUTH)                      # (E, T, 6)
    E, T, _ = t.shape
    rng = np.random.default_rng(SEED)

    # fixed friend subset
    friend = np.zeros(T, bool)
    idx = rng.choice(T, size=int(round(T * FRIEND_FRAC)), replace=False)
    friend[idx] = True

    ndet = []
    dets = []                               # list of (x,y,z)
    for e in range(E):
        n = 0
        for k in range(T):
            if not friend[k]:
                continue
            p = t[e, k, :3]
            if np.isnan(p[0]):
                continue                    # friend not airborne this epoch
            if rng.random() > P_REPLY:
                continue                    # transponder dropout this look
            q = p + rng.normal(0, IFF_POS_SIG, 3)
            dets.append((q[0], q[1], q[2])); n += 1
        ndet.append(n)

    maxdet = max(ndet)
    print(f"epochs={E}  friends={friend.sum()}/{T}  max replies/epoch={maxdet}  total={len(dets)}")

    # pad to a rectangular [E * maxdet * 3] block
    flat = []
    di = 0
    for e in range(E):
        for j in range(maxdet):
            if j < ndet[e]:
                flat.extend(dets[di]); di += 1
            else:
                flat.extend((0.0, 0.0, 0.0))

    with open("iff3.h", "w") as f:
        f.write("// iff3.h - Stage E IFF friend-reply stream (generated by gen_iff.py)\n")
        f.write("// One interrogation per epoch; each reply is a friend position [x,y,z] (m).\n")
        f.write("#ifndef IFF3_H\n#define IFF3_H\n")
        f.write(f"#define S3_IFF_NEPOCH {E}\n")
        f.write(f"#define S3_IFF_MAXDET {maxdet}\n\n")
        f.write(f"static const int s3_iff_ndet[{E}] = {{\n")
        for i in range(0, E, 12):
            f.write("  " + ", ".join(str(x) for x in ndet[i:i+12]) + ",\n")
        f.write("};\n")
        f.write(f"static const float s3_iff_det[{E*maxdet*3}] = {{\n")
        for i in range(0, len(flat), 6):
            f.write("  " + " ".join(f"{v:.7e}f," for v in flat[i:i+6]) + "\n")
        f.write("};\n")
        # friend truth (for host verification only; not used by the flight loop)
        f.write(f"static const int s3_friend[{T}] = {{\n")
        for i in range(0, T, 20):
            f.write("  " + ", ".join(str(int(x)) for x in friend[i:i+20]) + ",\n")
        f.write("};\n#endif // IFF3_H\n")

    np.save("friend_mask.npy", friend)
    print("wrote iff3.h and friend_mask.npy")

if __name__ == "__main__":
    main()
