// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_89_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        P_198,
        P_192,
        P_186,
        P_199,
        P_205,
        P_211,
        H_5_reload,
        P_197,
        P_191,
        P_185,
        P_200,
        P_206,
        P_212,
        H_4_reload,
        P_196,
        P_190,
        P_184,
        P_201,
        P_207,
        P_213,
        H_3_reload,
        P_195,
        P_189,
        P_183,
        P_202,
        P_208,
        P_214,
        H_2_reload,
        P_194,
        P_188,
        P_182,
        P_203,
        P_209,
        P_215,
        H_1_reload,
        P_193,
        P_187,
        P_181,
        P_204,
        P_210,
        P_216,
        H_reload,
        Ph_5_out,
        Ph_5_out_ap_vld,
        Ph_4_out,
        Ph_4_out_ap_vld,
        Ph_3_out,
        Ph_3_out_ap_vld,
        Ph_2_out,
        Ph_2_out_ap_vld,
        Ph_1_out,
        Ph_1_out_ap_vld,
        Ph_out,
        Ph_out_ap_vld,
        grp_fu_12431_p_din0,
        grp_fu_12431_p_din1,
        grp_fu_12431_p_opcode,
        grp_fu_12431_p_dout0,
        grp_fu_12431_p_ce,
        grp_fu_19351_p_din0,
        grp_fu_19351_p_din1,
        grp_fu_19351_p_opcode,
        grp_fu_19351_p_dout0,
        grp_fu_19351_p_ce,
        grp_fu_19355_p_din0,
        grp_fu_19355_p_din1,
        grp_fu_19355_p_opcode,
        grp_fu_19355_p_dout0,
        grp_fu_19355_p_ce,
        grp_fu_19359_p_din0,
        grp_fu_19359_p_din1,
        grp_fu_19359_p_opcode,
        grp_fu_19359_p_dout0,
        grp_fu_19359_p_ce,
        grp_fu_19363_p_din0,
        grp_fu_19363_p_din1,
        grp_fu_19363_p_opcode,
        grp_fu_19363_p_dout0,
        grp_fu_19363_p_ce,
        grp_fu_19367_p_din0,
        grp_fu_19367_p_din1,
        grp_fu_19367_p_opcode,
        grp_fu_19367_p_dout0,
        grp_fu_19367_p_ce,
        grp_fu_12435_p_din0,
        grp_fu_12435_p_din1,
        grp_fu_12435_p_dout0,
        grp_fu_12435_p_ce,
        grp_fu_19371_p_din0,
        grp_fu_19371_p_din1,
        grp_fu_19371_p_dout0,
        grp_fu_19371_p_ce,
        grp_fu_19375_p_din0,
        grp_fu_19375_p_din1,
        grp_fu_19375_p_dout0,
        grp_fu_19375_p_ce,
        grp_fu_19379_p_din0,
        grp_fu_19379_p_din1,
        grp_fu_19379_p_dout0,
        grp_fu_19379_p_ce,
        grp_fu_19383_p_din0,
        grp_fu_19383_p_din1,
        grp_fu_19383_p_dout0,
        grp_fu_19383_p_ce,
        grp_fu_19387_p_din0,
        grp_fu_19387_p_din1,
        grp_fu_19387_p_dout0,
        grp_fu_19387_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] P_198;
input  [31:0] P_192;
input  [31:0] P_186;
input  [31:0] P_199;
input  [31:0] P_205;
input  [31:0] P_211;
input  [31:0] H_5_reload;
input  [31:0] P_197;
input  [31:0] P_191;
input  [31:0] P_185;
input  [31:0] P_200;
input  [31:0] P_206;
input  [31:0] P_212;
input  [31:0] H_4_reload;
input  [31:0] P_196;
input  [31:0] P_190;
input  [31:0] P_184;
input  [31:0] P_201;
input  [31:0] P_207;
input  [31:0] P_213;
input  [31:0] H_3_reload;
input  [31:0] P_195;
input  [31:0] P_189;
input  [31:0] P_183;
input  [31:0] P_202;
input  [31:0] P_208;
input  [31:0] P_214;
input  [31:0] H_2_reload;
input  [31:0] P_194;
input  [31:0] P_188;
input  [31:0] P_182;
input  [31:0] P_203;
input  [31:0] P_209;
input  [31:0] P_215;
input  [31:0] H_1_reload;
input  [31:0] P_193;
input  [31:0] P_187;
input  [31:0] P_181;
input  [31:0] P_204;
input  [31:0] P_210;
input  [31:0] P_216;
input  [31:0] H_reload;
output  [31:0] Ph_5_out;
output   Ph_5_out_ap_vld;
output  [31:0] Ph_4_out;
output   Ph_4_out_ap_vld;
output  [31:0] Ph_3_out;
output   Ph_3_out_ap_vld;
output  [31:0] Ph_2_out;
output   Ph_2_out_ap_vld;
output  [31:0] Ph_1_out;
output   Ph_1_out_ap_vld;
output  [31:0] Ph_out;
output   Ph_out_ap_vld;
output  [31:0] grp_fu_12431_p_din0;
output  [31:0] grp_fu_12431_p_din1;
output  [1:0] grp_fu_12431_p_opcode;
input  [31:0] grp_fu_12431_p_dout0;
output   grp_fu_12431_p_ce;
output  [31:0] grp_fu_19351_p_din0;
output  [31:0] grp_fu_19351_p_din1;
output  [0:0] grp_fu_19351_p_opcode;
input  [31:0] grp_fu_19351_p_dout0;
output   grp_fu_19351_p_ce;
output  [31:0] grp_fu_19355_p_din0;
output  [31:0] grp_fu_19355_p_din1;
output  [0:0] grp_fu_19355_p_opcode;
input  [31:0] grp_fu_19355_p_dout0;
output   grp_fu_19355_p_ce;
output  [31:0] grp_fu_19359_p_din0;
output  [31:0] grp_fu_19359_p_din1;
output  [0:0] grp_fu_19359_p_opcode;
input  [31:0] grp_fu_19359_p_dout0;
output   grp_fu_19359_p_ce;
output  [31:0] grp_fu_19363_p_din0;
output  [31:0] grp_fu_19363_p_din1;
output  [0:0] grp_fu_19363_p_opcode;
input  [31:0] grp_fu_19363_p_dout0;
output   grp_fu_19363_p_ce;
output  [31:0] grp_fu_19367_p_din0;
output  [31:0] grp_fu_19367_p_din1;
output  [0:0] grp_fu_19367_p_opcode;
input  [31:0] grp_fu_19367_p_dout0;
output   grp_fu_19367_p_ce;
output  [31:0] grp_fu_12435_p_din0;
output  [31:0] grp_fu_12435_p_din1;
input  [31:0] grp_fu_12435_p_dout0;
output   grp_fu_12435_p_ce;
output  [31:0] grp_fu_19371_p_din0;
output  [31:0] grp_fu_19371_p_din1;
input  [31:0] grp_fu_19371_p_dout0;
output   grp_fu_19371_p_ce;
output  [31:0] grp_fu_19375_p_din0;
output  [31:0] grp_fu_19375_p_din1;
input  [31:0] grp_fu_19375_p_dout0;
output   grp_fu_19375_p_ce;
output  [31:0] grp_fu_19379_p_din0;
output  [31:0] grp_fu_19379_p_din1;
input  [31:0] grp_fu_19379_p_dout0;
output   grp_fu_19379_p_ce;
output  [31:0] grp_fu_19383_p_din0;
output  [31:0] grp_fu_19383_p_din1;
input  [31:0] grp_fu_19383_p_dout0;
output   grp_fu_19383_p_ce;
output  [31:0] grp_fu_19387_p_din0;
output  [31:0] grp_fu_19387_p_din1;
input  [31:0] grp_fu_19387_p_dout0;
output   grp_fu_19387_p_ce;

reg ap_idle;
reg Ph_5_out_ap_vld;
reg Ph_4_out_ap_vld;
reg Ph_3_out_ap_vld;
reg Ph_2_out_ap_vld;
reg Ph_1_out_ap_vld;
reg Ph_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln89_fu_511_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] i_2_reg_878;
reg   [2:0] i_2_reg_878_pp0_iter1_reg;
reg   [2:0] i_2_reg_878_pp0_iter2_reg;
reg   [2:0] i_2_reg_878_pp0_iter3_reg;
reg   [2:0] i_2_reg_878_pp0_iter4_reg;
reg   [2:0] i_2_reg_878_pp0_iter5_reg;
reg   [2:0] i_2_reg_878_pp0_iter6_reg;
reg   [2:0] i_2_reg_878_pp0_iter7_reg;
reg   [2:0] i_2_reg_878_pp0_iter8_reg;
reg   [2:0] i_2_reg_878_pp0_iter9_reg;
reg   [2:0] i_2_reg_878_pp0_iter10_reg;
reg   [2:0] i_2_reg_878_pp0_iter11_reg;
reg   [2:0] i_2_reg_878_pp0_iter12_reg;
reg   [2:0] i_2_reg_878_pp0_iter13_reg;
reg   [2:0] i_2_reg_878_pp0_iter14_reg;
reg   [2:0] i_2_reg_878_pp0_iter15_reg;
reg   [2:0] i_2_reg_878_pp0_iter16_reg;
reg   [2:0] i_2_reg_878_pp0_iter17_reg;
reg   [2:0] i_2_reg_878_pp0_iter18_reg;
reg   [2:0] i_2_reg_878_pp0_iter19_reg;
reg   [2:0] i_2_reg_878_pp0_iter20_reg;
reg   [2:0] i_2_reg_878_pp0_iter21_reg;
reg   [2:0] i_2_reg_878_pp0_iter22_reg;
reg   [2:0] i_2_reg_878_pp0_iter23_reg;
reg   [2:0] i_2_reg_878_pp0_iter24_reg;
reg   [2:0] i_2_reg_878_pp0_iter25_reg;
reg   [2:0] i_2_reg_878_pp0_iter26_reg;
reg   [0:0] icmp_ln89_reg_887;
reg   [0:0] icmp_ln89_reg_887_pp0_iter1_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter2_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter3_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter4_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter5_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter6_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter7_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter8_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter9_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter10_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter11_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter12_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter13_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter14_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter15_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter16_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter17_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter18_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter19_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter20_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter21_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter22_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter23_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter24_reg;
reg   [0:0] icmp_ln89_reg_887_pp0_iter25_reg;
wire   [31:0] tmp_s_fu_523_p8;
reg   [31:0] tmp_s_reg_891;
reg   [31:0] mul_i1_reg_896;
wire   [31:0] tmp_2_fu_546_p8;
reg   [31:0] tmp_2_reg_901;
reg   [31:0] acc_reg_906;
reg   [31:0] mul_i11_1_reg_911;
wire   [31:0] tmp_3_fu_557_p8;
reg   [31:0] tmp_3_reg_916;
reg   [31:0] acc_1_reg_921;
reg   [31:0] mul_i11_2_reg_926;
wire   [31:0] tmp_4_fu_568_p8;
reg   [31:0] tmp_4_reg_931;
reg   [31:0] acc_2_reg_936;
reg   [31:0] mul_i11_3_reg_941;
wire   [31:0] tmp_5_fu_579_p8;
reg   [31:0] tmp_5_reg_946;
reg   [31:0] acc_3_reg_951;
reg   [31:0] mul_i11_4_reg_956;
wire   [31:0] tmp_6_fu_590_p8;
reg   [31:0] tmp_6_reg_961;
reg   [31:0] acc_4_reg_966;
reg   [31:0] mul_i11_5_reg_971;
reg   [2:0] i_fu_132;
wire   [2:0] add_ln89_fu_517_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0;
reg   [31:0] Ph_fu_136;
reg   [31:0] Ph_1_fu_140;
reg   [31:0] Ph_2_fu_144;
reg   [31:0] Ph_3_fu_148;
reg   [31:0] Ph_4_fu_152;
reg   [31:0] Ph_5_fu_156;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U709(
    .din0(P_198),
    .din1(P_192),
    .din2(P_186),
    .din3(P_199),
    .din4(P_205),
    .din5(P_211),
    .din6(ap_sig_allocacmp_i_2),
    .dout(tmp_s_fu_523_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U710(
    .din0(P_197),
    .din1(P_191),
    .din2(P_185),
    .din3(P_200),
    .din4(P_206),
    .din5(P_212),
    .din6(i_2_reg_878_pp0_iter3_reg),
    .dout(tmp_2_fu_546_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U711(
    .din0(P_196),
    .din1(P_190),
    .din2(P_184),
    .din3(P_201),
    .din4(P_207),
    .din5(P_213),
    .din6(i_2_reg_878_pp0_iter7_reg),
    .dout(tmp_3_fu_557_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U712(
    .din0(P_195),
    .din1(P_189),
    .din2(P_183),
    .din3(P_202),
    .din4(P_208),
    .din5(P_214),
    .din6(i_2_reg_878_pp0_iter11_reg),
    .dout(tmp_4_fu_568_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U713(
    .din0(P_194),
    .din1(P_188),
    .din2(P_182),
    .din3(P_203),
    .din4(P_209),
    .din5(P_215),
    .din6(i_2_reg_878_pp0_iter15_reg),
    .dout(tmp_5_fu_579_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U714(
    .din0(P_193),
    .din1(P_187),
    .din2(P_181),
    .din3(P_204),
    .din4(P_210),
    .din5(P_216),
    .din6(i_2_reg_878_pp0_iter19_reg),
    .dout(tmp_6_fu_590_p8)
);

ekf_batch_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter26_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_511_p2 == 1'd0))) begin
            i_fu_132 <= add_ln89_fu_517_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_132 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((i_2_reg_878_pp0_iter26_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        Ph_1_fu_140 <= grp_fu_19367_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((i_2_reg_878_pp0_iter26_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        Ph_2_fu_144 <= grp_fu_19367_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((i_2_reg_878_pp0_iter26_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        Ph_3_fu_148 <= grp_fu_19367_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((i_2_reg_878_pp0_iter26_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        Ph_4_fu_152 <= grp_fu_19367_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1) & ((i_2_reg_878_pp0_iter26_reg == 3'd5) | ((i_2_reg_878_pp0_iter26_reg == 3'd6) | (i_2_reg_878_pp0_iter26_reg == 3'd7))))) begin
        Ph_5_fu_156 <= grp_fu_19367_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((i_2_reg_878_pp0_iter26_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        Ph_fu_136 <= grp_fu_19367_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_1_reg_921 <= grp_fu_19351_p_dout0;
        acc_2_reg_936 <= grp_fu_19355_p_dout0;
        acc_3_reg_951 <= grp_fu_19359_p_dout0;
        acc_4_reg_966 <= grp_fu_19363_p_dout0;
        acc_reg_906 <= grp_fu_12431_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        i_2_reg_878_pp0_iter10_reg <= i_2_reg_878_pp0_iter9_reg;
        i_2_reg_878_pp0_iter11_reg <= i_2_reg_878_pp0_iter10_reg;
        i_2_reg_878_pp0_iter12_reg <= i_2_reg_878_pp0_iter11_reg;
        i_2_reg_878_pp0_iter13_reg <= i_2_reg_878_pp0_iter12_reg;
        i_2_reg_878_pp0_iter14_reg <= i_2_reg_878_pp0_iter13_reg;
        i_2_reg_878_pp0_iter15_reg <= i_2_reg_878_pp0_iter14_reg;
        i_2_reg_878_pp0_iter16_reg <= i_2_reg_878_pp0_iter15_reg;
        i_2_reg_878_pp0_iter17_reg <= i_2_reg_878_pp0_iter16_reg;
        i_2_reg_878_pp0_iter18_reg <= i_2_reg_878_pp0_iter17_reg;
        i_2_reg_878_pp0_iter19_reg <= i_2_reg_878_pp0_iter18_reg;
        i_2_reg_878_pp0_iter20_reg <= i_2_reg_878_pp0_iter19_reg;
        i_2_reg_878_pp0_iter21_reg <= i_2_reg_878_pp0_iter20_reg;
        i_2_reg_878_pp0_iter22_reg <= i_2_reg_878_pp0_iter21_reg;
        i_2_reg_878_pp0_iter23_reg <= i_2_reg_878_pp0_iter22_reg;
        i_2_reg_878_pp0_iter24_reg <= i_2_reg_878_pp0_iter23_reg;
        i_2_reg_878_pp0_iter25_reg <= i_2_reg_878_pp0_iter24_reg;
        i_2_reg_878_pp0_iter26_reg <= i_2_reg_878_pp0_iter25_reg;
        i_2_reg_878_pp0_iter2_reg <= i_2_reg_878_pp0_iter1_reg;
        i_2_reg_878_pp0_iter3_reg <= i_2_reg_878_pp0_iter2_reg;
        i_2_reg_878_pp0_iter4_reg <= i_2_reg_878_pp0_iter3_reg;
        i_2_reg_878_pp0_iter5_reg <= i_2_reg_878_pp0_iter4_reg;
        i_2_reg_878_pp0_iter6_reg <= i_2_reg_878_pp0_iter5_reg;
        i_2_reg_878_pp0_iter7_reg <= i_2_reg_878_pp0_iter6_reg;
        i_2_reg_878_pp0_iter8_reg <= i_2_reg_878_pp0_iter7_reg;
        i_2_reg_878_pp0_iter9_reg <= i_2_reg_878_pp0_iter8_reg;
        icmp_ln89_reg_887_pp0_iter10_reg <= icmp_ln89_reg_887_pp0_iter9_reg;
        icmp_ln89_reg_887_pp0_iter11_reg <= icmp_ln89_reg_887_pp0_iter10_reg;
        icmp_ln89_reg_887_pp0_iter12_reg <= icmp_ln89_reg_887_pp0_iter11_reg;
        icmp_ln89_reg_887_pp0_iter13_reg <= icmp_ln89_reg_887_pp0_iter12_reg;
        icmp_ln89_reg_887_pp0_iter14_reg <= icmp_ln89_reg_887_pp0_iter13_reg;
        icmp_ln89_reg_887_pp0_iter15_reg <= icmp_ln89_reg_887_pp0_iter14_reg;
        icmp_ln89_reg_887_pp0_iter16_reg <= icmp_ln89_reg_887_pp0_iter15_reg;
        icmp_ln89_reg_887_pp0_iter17_reg <= icmp_ln89_reg_887_pp0_iter16_reg;
        icmp_ln89_reg_887_pp0_iter18_reg <= icmp_ln89_reg_887_pp0_iter17_reg;
        icmp_ln89_reg_887_pp0_iter19_reg <= icmp_ln89_reg_887_pp0_iter18_reg;
        icmp_ln89_reg_887_pp0_iter20_reg <= icmp_ln89_reg_887_pp0_iter19_reg;
        icmp_ln89_reg_887_pp0_iter21_reg <= icmp_ln89_reg_887_pp0_iter20_reg;
        icmp_ln89_reg_887_pp0_iter22_reg <= icmp_ln89_reg_887_pp0_iter21_reg;
        icmp_ln89_reg_887_pp0_iter23_reg <= icmp_ln89_reg_887_pp0_iter22_reg;
        icmp_ln89_reg_887_pp0_iter24_reg <= icmp_ln89_reg_887_pp0_iter23_reg;
        icmp_ln89_reg_887_pp0_iter25_reg <= icmp_ln89_reg_887_pp0_iter24_reg;
        icmp_ln89_reg_887_pp0_iter2_reg <= icmp_ln89_reg_887_pp0_iter1_reg;
        icmp_ln89_reg_887_pp0_iter3_reg <= icmp_ln89_reg_887_pp0_iter2_reg;
        icmp_ln89_reg_887_pp0_iter4_reg <= icmp_ln89_reg_887_pp0_iter3_reg;
        icmp_ln89_reg_887_pp0_iter5_reg <= icmp_ln89_reg_887_pp0_iter4_reg;
        icmp_ln89_reg_887_pp0_iter6_reg <= icmp_ln89_reg_887_pp0_iter5_reg;
        icmp_ln89_reg_887_pp0_iter7_reg <= icmp_ln89_reg_887_pp0_iter6_reg;
        icmp_ln89_reg_887_pp0_iter8_reg <= icmp_ln89_reg_887_pp0_iter7_reg;
        icmp_ln89_reg_887_pp0_iter9_reg <= icmp_ln89_reg_887_pp0_iter8_reg;
        mul_i11_1_reg_911 <= grp_fu_19371_p_dout0;
        mul_i11_2_reg_926 <= grp_fu_19375_p_dout0;
        mul_i11_3_reg_941 <= grp_fu_19379_p_dout0;
        mul_i11_4_reg_956 <= grp_fu_19383_p_dout0;
        mul_i11_5_reg_971 <= grp_fu_19387_p_dout0;
        mul_i1_reg_896 <= grp_fu_12435_p_dout0;
        tmp_2_reg_901 <= tmp_2_fu_546_p8;
        tmp_3_reg_916 <= tmp_3_fu_557_p8;
        tmp_4_reg_931 <= tmp_4_fu_568_p8;
        tmp_5_reg_946 <= tmp_5_fu_579_p8;
        tmp_6_reg_961 <= tmp_6_fu_590_p8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_2_reg_878 <= ap_sig_allocacmp_i_2;
        i_2_reg_878_pp0_iter1_reg <= i_2_reg_878;
        icmp_ln89_reg_887 <= icmp_ln89_fu_511_p2;
        icmp_ln89_reg_887_pp0_iter1_reg <= icmp_ln89_reg_887;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_511_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_s_reg_891 <= tmp_s_fu_523_p8;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_887_pp0_iter25_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Ph_1_out_ap_vld = 1'b1;
    end else begin
        Ph_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_887_pp0_iter25_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Ph_2_out_ap_vld = 1'b1;
    end else begin
        Ph_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_887_pp0_iter25_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Ph_3_out_ap_vld = 1'b1;
    end else begin
        Ph_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_887_pp0_iter25_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Ph_4_out_ap_vld = 1'b1;
    end else begin
        Ph_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_887_pp0_iter25_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Ph_5_out_ap_vld = 1'b1;
    end else begin
        Ph_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_887_pp0_iter25_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Ph_out_ap_vld = 1'b1;
    end else begin
        Ph_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_511_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter26_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_132;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Ph_1_out = Ph_1_fu_140;

assign Ph_2_out = Ph_2_fu_144;

assign Ph_3_out = Ph_3_fu_148;

assign Ph_4_out = Ph_4_fu_152;

assign Ph_5_out = Ph_5_fu_156;

assign Ph_out = Ph_fu_136;

assign add_ln89_fu_517_p2 = (ap_sig_allocacmp_i_2 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_12431_p_ce = 1'b1;

assign grp_fu_12431_p_din0 = mul_i1_reg_896;

assign grp_fu_12431_p_din1 = 32'd0;

assign grp_fu_12431_p_opcode = 2'd0;

assign grp_fu_12435_p_ce = 1'b1;

assign grp_fu_12435_p_din0 = tmp_s_reg_891;

assign grp_fu_12435_p_din1 = H_5_reload;

assign grp_fu_19351_p_ce = 1'b1;

assign grp_fu_19351_p_din0 = acc_reg_906;

assign grp_fu_19351_p_din1 = mul_i11_1_reg_911;

assign grp_fu_19351_p_opcode = 2'd0;

assign grp_fu_19355_p_ce = 1'b1;

assign grp_fu_19355_p_din0 = acc_1_reg_921;

assign grp_fu_19355_p_din1 = mul_i11_2_reg_926;

assign grp_fu_19355_p_opcode = 2'd0;

assign grp_fu_19359_p_ce = 1'b1;

assign grp_fu_19359_p_din0 = acc_2_reg_936;

assign grp_fu_19359_p_din1 = mul_i11_3_reg_941;

assign grp_fu_19359_p_opcode = 2'd0;

assign grp_fu_19363_p_ce = 1'b1;

assign grp_fu_19363_p_din0 = acc_3_reg_951;

assign grp_fu_19363_p_din1 = mul_i11_4_reg_956;

assign grp_fu_19363_p_opcode = 2'd0;

assign grp_fu_19367_p_ce = 1'b1;

assign grp_fu_19367_p_din0 = acc_4_reg_966;

assign grp_fu_19367_p_din1 = mul_i11_5_reg_971;

assign grp_fu_19367_p_opcode = 2'd0;

assign grp_fu_19371_p_ce = 1'b1;

assign grp_fu_19371_p_din0 = tmp_2_reg_901;

assign grp_fu_19371_p_din1 = H_4_reload;

assign grp_fu_19375_p_ce = 1'b1;

assign grp_fu_19375_p_din0 = tmp_3_reg_916;

assign grp_fu_19375_p_din1 = H_3_reload;

assign grp_fu_19379_p_ce = 1'b1;

assign grp_fu_19379_p_din0 = tmp_4_reg_931;

assign grp_fu_19379_p_din1 = H_2_reload;

assign grp_fu_19383_p_ce = 1'b1;

assign grp_fu_19383_p_din0 = tmp_5_reg_946;

assign grp_fu_19383_p_din1 = H_1_reload;

assign grp_fu_19387_p_ce = 1'b1;

assign grp_fu_19387_p_din0 = tmp_6_reg_961;

assign grp_fu_19387_p_din1 = H_reload;

assign icmp_ln89_fu_511_p2 = ((ap_sig_allocacmp_i_2 == 3'd6) ? 1'b1 : 1'b0);

endmodule //ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_89_1
