// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_173_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_5_load_3,
        local_load_1,
        local_1_load_1,
        local_2_load_3,
        local_3_load_3,
        local_4_load_3,
        x_31,
        x_30,
        x_29,
        x_28,
        x_27,
        x_26,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] local_5_load_3;
input  [31:0] local_load_1;
input  [31:0] local_1_load_1;
input  [31:0] local_2_load_3;
input  [31:0] local_3_load_3;
input  [31:0] local_4_load_3;
input  [31:0] x_31;
input  [31:0] x_30;
input  [31:0] x_29;
input  [31:0] x_28;
input  [31:0] x_27;
input  [31:0] x_26;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] p_out2;
output   p_out2_ap_vld;
output  [31:0] p_out3;
output   p_out3_ap_vld;
output  [31:0] p_out4;
output   p_out4_ap_vld;
output  [31:0] p_out5;
output   p_out5_ap_vld;

reg ap_idle;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln173_fu_252_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_fu_72;
wire   [2:0] add_ln173_fu_258_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_9;
wire   [2:0] i_9_load_fu_249_p1;
reg   [31:0] empty_fu_76;
wire   [31:0] tmp_56_fu_264_p8;
reg   [31:0] empty_47_fu_80;
reg   [31:0] empty_48_fu_84;
reg   [31:0] empty_49_fu_88;
reg   [31:0] empty_50_fu_92;
reg   [31:0] empty_51_fu_96;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_120;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1369(
    .din0(x_31),
    .din1(x_30),
    .din2(x_29),
    .din3(x_28),
    .din4(x_27),
    .din5(x_26),
    .din6(ap_sig_allocacmp_i_9),
    .dout(tmp_56_fu_264_p8)
);

ekf_batch_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((i_9_load_fu_249_p1 == 3'd3) & (icmp_ln173_fu_252_p2 == 1'd0))) begin
            empty_47_fu_80 <= tmp_56_fu_264_p8;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_47_fu_80 <= local_3_load_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((i_9_load_fu_249_p1 == 3'd2) & (icmp_ln173_fu_252_p2 == 1'd0))) begin
            empty_48_fu_84 <= tmp_56_fu_264_p8;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_48_fu_84 <= local_2_load_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((i_9_load_fu_249_p1 == 3'd1) & (icmp_ln173_fu_252_p2 == 1'd0))) begin
            empty_49_fu_88 <= tmp_56_fu_264_p8;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_49_fu_88 <= local_1_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((i_9_load_fu_249_p1 == 3'd0) & (icmp_ln173_fu_252_p2 == 1'd0))) begin
            empty_50_fu_92 <= tmp_56_fu_264_p8;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_50_fu_92 <= local_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((1'b1 == ap_condition_120)) begin
            empty_51_fu_96 <= tmp_56_fu_264_p8;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_51_fu_96 <= local_5_load_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((i_9_load_fu_249_p1 == 3'd4) & (icmp_ln173_fu_252_p2 == 1'd0))) begin
            empty_fu_76 <= tmp_56_fu_264_p8;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_76 <= local_4_load_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln173_fu_252_p2 == 1'd0)) begin
            i_fu_72 <= add_ln173_fu_258_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_72 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_9 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_9 = i_fu_72;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln173_fu_258_p2 = (ap_sig_allocacmp_i_9 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_condition_120 = (~(i_9_load_fu_249_p1 == 3'd1) & ~(i_9_load_fu_249_p1 == 3'd2) & ~(i_9_load_fu_249_p1 == 3'd3) & ~(i_9_load_fu_249_p1 == 3'd4) & ~(i_9_load_fu_249_p1 == 3'd0) & (icmp_ln173_fu_252_p2 == 1'd0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_9_load_fu_249_p1 = ap_sig_allocacmp_i_9;

assign icmp_ln173_fu_252_p2 = ((ap_sig_allocacmp_i_9 == 3'd6) ? 1'b1 : 1'b0);

assign p_out = empty_51_fu_96;

assign p_out1 = empty_50_fu_92;

assign p_out2 = empty_49_fu_88;

assign p_out3 = empty_48_fu_84;

assign p_out4 = empty_47_fu_80;

assign p_out5 = empty_fu_76;

endmodule //ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_173_9
