// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_117_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        P_181,
        P_182,
        P_183,
        P_184,
        P_185,
        P_186,
        P_187,
        P_188,
        P_189,
        P_190,
        P_191,
        P_192,
        P_193,
        P_194,
        P_195,
        P_196,
        P_197,
        P_198,
        P_199,
        P_200,
        P_201,
        P_202,
        P_203,
        P_204,
        P_205,
        P_206,
        P_207,
        P_208,
        P_209,
        P_210,
        P_211,
        P_212,
        P_213,
        P_214,
        P_215,
        P_216,
        mux_case_521593212_reload,
        mux_case_521723249_reload,
        mux_case_521853285_reload,
        mux_case_521983321_reload,
        mux_case_522113357_reload,
        mux_case_522243393_reload,
        K_5_reload,
        mux_case_421573206_reload,
        mux_case_421703243_reload,
        mux_case_421833279_reload,
        mux_case_421963315_reload,
        mux_case_422093351_reload,
        mux_case_422223387_reload,
        K_4_reload,
        mux_case_321553200_reload,
        mux_case_321683237_reload,
        mux_case_321813273_reload,
        mux_case_321943309_reload,
        mux_case_322073345_reload,
        mux_case_322203381_reload,
        K_3_reload,
        mux_case_221533194_reload,
        mux_case_221663231_reload,
        mux_case_221793267_reload,
        mux_case_221923303_reload,
        mux_case_222053339_reload,
        mux_case_222183375_reload,
        K_2_reload,
        mux_case_121513188_reload,
        mux_case_121643225_reload,
        mux_case_121773261_reload,
        mux_case_121903297_reload,
        mux_case_122033333_reload,
        mux_case_122163369_reload,
        K_1_reload,
        K_reload,
        s_2,
        mux_case_021493182_reload,
        mux_case_021623219_reload,
        mux_case_021753255_reload,
        mux_case_021883291_reload,
        mux_case_022013327_reload,
        mux_case_022143363_reload,
        P_318_out,
        P_318_out_ap_vld,
        P_317_out,
        P_317_out_ap_vld,
        P_316_out,
        P_316_out_ap_vld,
        P_315_out,
        P_315_out_ap_vld,
        P_314_out,
        P_314_out_ap_vld,
        P_313_out,
        P_313_out_ap_vld,
        P_312_out,
        P_312_out_ap_vld,
        P_311_out,
        P_311_out_ap_vld,
        P_310_out,
        P_310_out_ap_vld,
        P_309_out,
        P_309_out_ap_vld,
        P_308_out,
        P_308_out_ap_vld,
        P_307_out,
        P_307_out_ap_vld,
        P_306_out,
        P_306_out_ap_vld,
        P_305_out,
        P_305_out_ap_vld,
        P_304_out,
        P_304_out_ap_vld,
        P_303_out,
        P_303_out_ap_vld,
        P_302_out,
        P_302_out_ap_vld,
        P_301_out,
        P_301_out_ap_vld,
        P_300_out,
        P_300_out_ap_vld,
        P_299_out,
        P_299_out_ap_vld,
        P_298_out,
        P_298_out_ap_vld,
        P_297_out,
        P_297_out_ap_vld,
        P_296_out,
        P_296_out_ap_vld,
        P_295_out,
        P_295_out_ap_vld,
        P_294_out,
        P_294_out_ap_vld,
        P_293_out,
        P_293_out_ap_vld,
        P_292_out,
        P_292_out_ap_vld,
        P_291_out,
        P_291_out_ap_vld,
        P_290_out,
        P_290_out_ap_vld,
        P_289_out,
        P_289_out_ap_vld,
        P_288_out,
        P_288_out_ap_vld,
        P_287_out,
        P_287_out_ap_vld,
        P_286_out,
        P_286_out_ap_vld,
        P_285_out,
        P_285_out_ap_vld,
        P_284_out,
        P_284_out_ap_vld,
        P_283_out,
        P_283_out_ap_vld,
        grp_fu_12431_p_din0,
        grp_fu_12431_p_din1,
        grp_fu_12431_p_opcode,
        grp_fu_12431_p_dout0,
        grp_fu_12431_p_ce,
        grp_fu_19351_p_din0,
        grp_fu_19351_p_din1,
        grp_fu_19351_p_opcode,
        grp_fu_19351_p_dout0,
        grp_fu_19351_p_ce,
        grp_fu_19355_p_din0,
        grp_fu_19355_p_din1,
        grp_fu_19355_p_opcode,
        grp_fu_19355_p_dout0,
        grp_fu_19355_p_ce,
        grp_fu_19359_p_din0,
        grp_fu_19359_p_din1,
        grp_fu_19359_p_opcode,
        grp_fu_19359_p_dout0,
        grp_fu_19359_p_ce,
        grp_fu_19363_p_din0,
        grp_fu_19363_p_din1,
        grp_fu_19363_p_opcode,
        grp_fu_19363_p_dout0,
        grp_fu_19363_p_ce,
        grp_fu_19367_p_din0,
        grp_fu_19367_p_din1,
        grp_fu_19367_p_opcode,
        grp_fu_19367_p_dout0,
        grp_fu_19367_p_ce,
        grp_fu_12435_p_din0,
        grp_fu_12435_p_din1,
        grp_fu_12435_p_dout0,
        grp_fu_12435_p_ce,
        grp_fu_19371_p_din0,
        grp_fu_19371_p_din1,
        grp_fu_19371_p_dout0,
        grp_fu_19371_p_ce,
        grp_fu_19375_p_din0,
        grp_fu_19375_p_din1,
        grp_fu_19375_p_dout0,
        grp_fu_19375_p_ce,
        grp_fu_19379_p_din0,
        grp_fu_19379_p_din1,
        grp_fu_19379_p_dout0,
        grp_fu_19379_p_ce,
        grp_fu_19383_p_din0,
        grp_fu_19383_p_din1,
        grp_fu_19383_p_dout0,
        grp_fu_19383_p_ce,
        grp_fu_19387_p_din0,
        grp_fu_19387_p_din1,
        grp_fu_19387_p_dout0,
        grp_fu_19387_p_ce,
        grp_fu_19347_p_din0,
        grp_fu_19347_p_din1,
        grp_fu_19347_p_dout0,
        grp_fu_19347_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] P_181;
input  [31:0] P_182;
input  [31:0] P_183;
input  [31:0] P_184;
input  [31:0] P_185;
input  [31:0] P_186;
input  [31:0] P_187;
input  [31:0] P_188;
input  [31:0] P_189;
input  [31:0] P_190;
input  [31:0] P_191;
input  [31:0] P_192;
input  [31:0] P_193;
input  [31:0] P_194;
input  [31:0] P_195;
input  [31:0] P_196;
input  [31:0] P_197;
input  [31:0] P_198;
input  [31:0] P_199;
input  [31:0] P_200;
input  [31:0] P_201;
input  [31:0] P_202;
input  [31:0] P_203;
input  [31:0] P_204;
input  [31:0] P_205;
input  [31:0] P_206;
input  [31:0] P_207;
input  [31:0] P_208;
input  [31:0] P_209;
input  [31:0] P_210;
input  [31:0] P_211;
input  [31:0] P_212;
input  [31:0] P_213;
input  [31:0] P_214;
input  [31:0] P_215;
input  [31:0] P_216;
input  [31:0] mux_case_521593212_reload;
input  [31:0] mux_case_521723249_reload;
input  [31:0] mux_case_521853285_reload;
input  [31:0] mux_case_521983321_reload;
input  [31:0] mux_case_522113357_reload;
input  [31:0] mux_case_522243393_reload;
input  [31:0] K_5_reload;
input  [31:0] mux_case_421573206_reload;
input  [31:0] mux_case_421703243_reload;
input  [31:0] mux_case_421833279_reload;
input  [31:0] mux_case_421963315_reload;
input  [31:0] mux_case_422093351_reload;
input  [31:0] mux_case_422223387_reload;
input  [31:0] K_4_reload;
input  [31:0] mux_case_321553200_reload;
input  [31:0] mux_case_321683237_reload;
input  [31:0] mux_case_321813273_reload;
input  [31:0] mux_case_321943309_reload;
input  [31:0] mux_case_322073345_reload;
input  [31:0] mux_case_322203381_reload;
input  [31:0] K_3_reload;
input  [31:0] mux_case_221533194_reload;
input  [31:0] mux_case_221663231_reload;
input  [31:0] mux_case_221793267_reload;
input  [31:0] mux_case_221923303_reload;
input  [31:0] mux_case_222053339_reload;
input  [31:0] mux_case_222183375_reload;
input  [31:0] K_2_reload;
input  [31:0] mux_case_121513188_reload;
input  [31:0] mux_case_121643225_reload;
input  [31:0] mux_case_121773261_reload;
input  [31:0] mux_case_121903297_reload;
input  [31:0] mux_case_122033333_reload;
input  [31:0] mux_case_122163369_reload;
input  [31:0] K_1_reload;
input  [31:0] K_reload;
input  [31:0] s_2;
input  [31:0] mux_case_021493182_reload;
input  [31:0] mux_case_021623219_reload;
input  [31:0] mux_case_021753255_reload;
input  [31:0] mux_case_021883291_reload;
input  [31:0] mux_case_022013327_reload;
input  [31:0] mux_case_022143363_reload;
output  [31:0] P_318_out;
output   P_318_out_ap_vld;
output  [31:0] P_317_out;
output   P_317_out_ap_vld;
output  [31:0] P_316_out;
output   P_316_out_ap_vld;
output  [31:0] P_315_out;
output   P_315_out_ap_vld;
output  [31:0] P_314_out;
output   P_314_out_ap_vld;
output  [31:0] P_313_out;
output   P_313_out_ap_vld;
output  [31:0] P_312_out;
output   P_312_out_ap_vld;
output  [31:0] P_311_out;
output   P_311_out_ap_vld;
output  [31:0] P_310_out;
output   P_310_out_ap_vld;
output  [31:0] P_309_out;
output   P_309_out_ap_vld;
output  [31:0] P_308_out;
output   P_308_out_ap_vld;
output  [31:0] P_307_out;
output   P_307_out_ap_vld;
output  [31:0] P_306_out;
output   P_306_out_ap_vld;
output  [31:0] P_305_out;
output   P_305_out_ap_vld;
output  [31:0] P_304_out;
output   P_304_out_ap_vld;
output  [31:0] P_303_out;
output   P_303_out_ap_vld;
output  [31:0] P_302_out;
output   P_302_out_ap_vld;
output  [31:0] P_301_out;
output   P_301_out_ap_vld;
output  [31:0] P_300_out;
output   P_300_out_ap_vld;
output  [31:0] P_299_out;
output   P_299_out_ap_vld;
output  [31:0] P_298_out;
output   P_298_out_ap_vld;
output  [31:0] P_297_out;
output   P_297_out_ap_vld;
output  [31:0] P_296_out;
output   P_296_out_ap_vld;
output  [31:0] P_295_out;
output   P_295_out_ap_vld;
output  [31:0] P_294_out;
output   P_294_out_ap_vld;
output  [31:0] P_293_out;
output   P_293_out_ap_vld;
output  [31:0] P_292_out;
output   P_292_out_ap_vld;
output  [31:0] P_291_out;
output   P_291_out_ap_vld;
output  [31:0] P_290_out;
output   P_290_out_ap_vld;
output  [31:0] P_289_out;
output   P_289_out_ap_vld;
output  [31:0] P_288_out;
output   P_288_out_ap_vld;
output  [31:0] P_287_out;
output   P_287_out_ap_vld;
output  [31:0] P_286_out;
output   P_286_out_ap_vld;
output  [31:0] P_285_out;
output   P_285_out_ap_vld;
output  [31:0] P_284_out;
output   P_284_out_ap_vld;
output  [31:0] P_283_out;
output   P_283_out_ap_vld;
output  [31:0] grp_fu_12431_p_din0;
output  [31:0] grp_fu_12431_p_din1;
output  [1:0] grp_fu_12431_p_opcode;
input  [31:0] grp_fu_12431_p_dout0;
output   grp_fu_12431_p_ce;
output  [31:0] grp_fu_19351_p_din0;
output  [31:0] grp_fu_19351_p_din1;
output  [0:0] grp_fu_19351_p_opcode;
input  [31:0] grp_fu_19351_p_dout0;
output   grp_fu_19351_p_ce;
output  [31:0] grp_fu_19355_p_din0;
output  [31:0] grp_fu_19355_p_din1;
output  [0:0] grp_fu_19355_p_opcode;
input  [31:0] grp_fu_19355_p_dout0;
output   grp_fu_19355_p_ce;
output  [31:0] grp_fu_19359_p_din0;
output  [31:0] grp_fu_19359_p_din1;
output  [0:0] grp_fu_19359_p_opcode;
input  [31:0] grp_fu_19359_p_dout0;
output   grp_fu_19359_p_ce;
output  [31:0] grp_fu_19363_p_din0;
output  [31:0] grp_fu_19363_p_din1;
output  [0:0] grp_fu_19363_p_opcode;
input  [31:0] grp_fu_19363_p_dout0;
output   grp_fu_19363_p_ce;
output  [31:0] grp_fu_19367_p_din0;
output  [31:0] grp_fu_19367_p_din1;
output  [0:0] grp_fu_19367_p_opcode;
input  [31:0] grp_fu_19367_p_dout0;
output   grp_fu_19367_p_ce;
output  [31:0] grp_fu_12435_p_din0;
output  [31:0] grp_fu_12435_p_din1;
input  [31:0] grp_fu_12435_p_dout0;
output   grp_fu_12435_p_ce;
output  [31:0] grp_fu_19371_p_din0;
output  [31:0] grp_fu_19371_p_din1;
input  [31:0] grp_fu_19371_p_dout0;
output   grp_fu_19371_p_ce;
output  [31:0] grp_fu_19375_p_din0;
output  [31:0] grp_fu_19375_p_din1;
input  [31:0] grp_fu_19375_p_dout0;
output   grp_fu_19375_p_ce;
output  [31:0] grp_fu_19379_p_din0;
output  [31:0] grp_fu_19379_p_din1;
input  [31:0] grp_fu_19379_p_dout0;
output   grp_fu_19379_p_ce;
output  [31:0] grp_fu_19383_p_din0;
output  [31:0] grp_fu_19383_p_din1;
input  [31:0] grp_fu_19383_p_dout0;
output   grp_fu_19383_p_ce;
output  [31:0] grp_fu_19387_p_din0;
output  [31:0] grp_fu_19387_p_din1;
input  [31:0] grp_fu_19387_p_dout0;
output   grp_fu_19387_p_ce;
output  [31:0] grp_fu_19347_p_din0;
output  [31:0] grp_fu_19347_p_din1;
input  [31:0] grp_fu_19347_p_dout0;
output   grp_fu_19347_p_ce;

reg ap_idle;
reg P_318_out_ap_vld;
reg P_317_out_ap_vld;
reg P_316_out_ap_vld;
reg P_315_out_ap_vld;
reg P_314_out_ap_vld;
reg P_313_out_ap_vld;
reg P_312_out_ap_vld;
reg P_311_out_ap_vld;
reg P_310_out_ap_vld;
reg P_309_out_ap_vld;
reg P_308_out_ap_vld;
reg P_307_out_ap_vld;
reg P_306_out_ap_vld;
reg P_305_out_ap_vld;
reg P_304_out_ap_vld;
reg P_303_out_ap_vld;
reg P_302_out_ap_vld;
reg P_301_out_ap_vld;
reg P_300_out_ap_vld;
reg P_299_out_ap_vld;
reg P_298_out_ap_vld;
reg P_297_out_ap_vld;
reg P_296_out_ap_vld;
reg P_295_out_ap_vld;
reg P_294_out_ap_vld;
reg P_293_out_ap_vld;
reg P_292_out_ap_vld;
reg P_291_out_ap_vld;
reg P_290_out_ap_vld;
reg P_289_out_ap_vld;
reg P_288_out_ap_vld;
reg P_287_out_ap_vld;
reg P_286_out_ap_vld;
reg P_285_out_ap_vld;
reg P_284_out_ap_vld;
reg P_283_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln117_fu_1380_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] i_12_reg_2285;
reg   [2:0] i_12_reg_2285_pp0_iter1_reg;
reg   [2:0] i_12_reg_2285_pp0_iter2_reg;
reg   [2:0] i_12_reg_2285_pp0_iter3_reg;
reg   [2:0] i_12_reg_2285_pp0_iter4_reg;
reg   [2:0] i_12_reg_2285_pp0_iter5_reg;
reg   [2:0] i_12_reg_2285_pp0_iter6_reg;
reg   [2:0] i_12_reg_2285_pp0_iter7_reg;
reg   [2:0] i_12_reg_2285_pp0_iter8_reg;
reg   [2:0] i_12_reg_2285_pp0_iter9_reg;
reg   [0:0] icmp_ln117_reg_2295;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter1_reg;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter2_reg;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter3_reg;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter4_reg;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter5_reg;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter6_reg;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter7_reg;
reg   [0:0] icmp_ln117_reg_2295_pp0_iter8_reg;
wire   [31:0] tmp_s_fu_1392_p8;
reg   [31:0] tmp_s_reg_2299;
reg   [31:0] mul102_i_reg_2304;
reg   [31:0] mul105_i_reg_2314;
reg   [31:0] mul105_i_1_reg_2319;
reg   [31:0] mul105_i_2_reg_2324;
reg   [31:0] mul105_i_3_reg_2329;
reg   [31:0] mul105_i_4_reg_2334;
reg   [31:0] mul105_i_5_reg_2339;
wire   [31:0] tmp_58_fu_1415_p8;
wire   [31:0] tmp_108_1_fu_1427_p8;
wire   [31:0] tmp_108_2_fu_1439_p8;
wire   [31:0] tmp_108_3_fu_1451_p8;
wire   [31:0] tmp_108_4_fu_1463_p8;
wire   [31:0] tmp_108_5_fu_1475_p8;
reg   [2:0] i_fu_266;
wire   [2:0] add_ln117_fu_1386_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_12;
wire    ap_block_pp0_stage0;
reg   [31:0] P_fu_270;
reg   [31:0] P_38_fu_274;
reg   [31:0] P_39_fu_278;
reg   [31:0] P_40_fu_282;
reg   [31:0] P_41_fu_286;
reg   [31:0] P_42_fu_290;
reg   [31:0] P_43_fu_294;
reg   [31:0] P_44_fu_298;
reg   [31:0] P_45_fu_302;
reg   [31:0] P_46_fu_306;
reg   [31:0] P_47_fu_310;
reg   [31:0] P_48_fu_314;
reg   [31:0] P_49_fu_318;
reg   [31:0] P_50_fu_322;
reg   [31:0] P_51_fu_326;
reg   [31:0] P_52_fu_330;
reg   [31:0] P_53_fu_334;
reg   [31:0] P_54_fu_338;
reg   [31:0] P_55_fu_342;
reg   [31:0] P_56_fu_346;
reg   [31:0] P_57_fu_350;
reg   [31:0] P_58_fu_354;
reg   [31:0] P_59_fu_358;
reg   [31:0] P_60_fu_362;
reg   [31:0] P_61_fu_366;
reg   [31:0] P_62_fu_370;
reg   [31:0] P_63_fu_374;
reg   [31:0] P_64_fu_378;
reg   [31:0] P_65_fu_382;
reg   [31:0] P_66_fu_386;
reg   [31:0] P_67_fu_390;
reg   [31:0] P_68_fu_394;
reg   [31:0] P_69_fu_398;
reg   [31:0] P_70_fu_402;
reg   [31:0] P_71_fu_406;
reg   [31:0] P_72_fu_410;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_1594;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1247(
    .din0(K_reload),
    .din1(K_1_reload),
    .din2(K_2_reload),
    .din3(K_3_reload),
    .din4(K_4_reload),
    .din5(K_5_reload),
    .din6(ap_sig_allocacmp_i_12),
    .dout(tmp_s_fu_1392_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1248(
    .din0(mux_case_021493182_reload),
    .din1(mux_case_021623219_reload),
    .din2(mux_case_021753255_reload),
    .din3(mux_case_021883291_reload),
    .din4(mux_case_022013327_reload),
    .din5(mux_case_022143363_reload),
    .din6(i_12_reg_2285_pp0_iter6_reg),
    .dout(tmp_58_fu_1415_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1249(
    .din0(mux_case_121513188_reload),
    .din1(mux_case_121643225_reload),
    .din2(mux_case_121773261_reload),
    .din3(mux_case_121903297_reload),
    .din4(mux_case_122033333_reload),
    .din5(mux_case_122163369_reload),
    .din6(i_12_reg_2285_pp0_iter6_reg),
    .dout(tmp_108_1_fu_1427_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1250(
    .din0(mux_case_221533194_reload),
    .din1(mux_case_221663231_reload),
    .din2(mux_case_221793267_reload),
    .din3(mux_case_221923303_reload),
    .din4(mux_case_222053339_reload),
    .din5(mux_case_222183375_reload),
    .din6(i_12_reg_2285_pp0_iter6_reg),
    .dout(tmp_108_2_fu_1439_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1251(
    .din0(mux_case_321553200_reload),
    .din1(mux_case_321683237_reload),
    .din2(mux_case_321813273_reload),
    .din3(mux_case_321943309_reload),
    .din4(mux_case_322073345_reload),
    .din5(mux_case_322203381_reload),
    .din6(i_12_reg_2285_pp0_iter6_reg),
    .dout(tmp_108_3_fu_1451_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1252(
    .din0(mux_case_421573206_reload),
    .din1(mux_case_421703243_reload),
    .din2(mux_case_421833279_reload),
    .din3(mux_case_421963315_reload),
    .din4(mux_case_422093351_reload),
    .din5(mux_case_422223387_reload),
    .din6(i_12_reg_2285_pp0_iter6_reg),
    .dout(tmp_108_4_fu_1463_p8)
);

ekf_batch_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U1253(
    .din0(mux_case_521593212_reload),
    .din1(mux_case_521723249_reload),
    .din2(mux_case_521853285_reload),
    .din3(mux_case_521983321_reload),
    .din4(mux_case_522113357_reload),
    .din5(mux_case_522243393_reload),
    .din6(i_12_reg_2285_pp0_iter6_reg),
    .dout(tmp_108_5_fu_1475_p8)
);

ekf_batch_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_38_fu_274 <= P_215;
        end else if ((1'b1 == ap_condition_1594)) begin
            P_38_fu_274 <= grp_fu_19363_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_39_fu_278 <= P_214;
        end else if ((1'b1 == ap_condition_1594)) begin
            P_39_fu_278 <= grp_fu_19359_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_40_fu_282 <= P_213;
        end else if ((1'b1 == ap_condition_1594)) begin
            P_40_fu_282 <= grp_fu_19355_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_41_fu_286 <= P_212;
        end else if ((1'b1 == ap_condition_1594)) begin
            P_41_fu_286 <= grp_fu_19351_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_42_fu_290 <= P_211;
        end else if ((1'b1 == ap_condition_1594)) begin
            P_42_fu_290 <= grp_fu_12431_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_43_fu_294 <= P_210;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd4))) begin
            P_43_fu_294 <= grp_fu_19367_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_44_fu_298 <= P_209;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd4))) begin
            P_44_fu_298 <= grp_fu_19363_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_45_fu_302 <= P_208;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd4))) begin
            P_45_fu_302 <= grp_fu_19359_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_46_fu_306 <= P_207;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd4))) begin
            P_46_fu_306 <= grp_fu_19355_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_47_fu_310 <= P_206;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd4))) begin
            P_47_fu_310 <= grp_fu_19351_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_48_fu_314 <= P_205;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd4))) begin
            P_48_fu_314 <= grp_fu_12431_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_49_fu_318 <= P_204;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd3))) begin
            P_49_fu_318 <= grp_fu_19367_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_50_fu_322 <= P_203;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd3))) begin
            P_50_fu_322 <= grp_fu_19363_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_51_fu_326 <= P_202;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd3))) begin
            P_51_fu_326 <= grp_fu_19359_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_52_fu_330 <= P_201;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd3))) begin
            P_52_fu_330 <= grp_fu_19355_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_53_fu_334 <= P_200;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd3))) begin
            P_53_fu_334 <= grp_fu_19351_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_54_fu_338 <= P_199;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd3))) begin
            P_54_fu_338 <= grp_fu_12431_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_55_fu_342 <= P_198;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd0))) begin
            P_55_fu_342 <= grp_fu_12431_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_56_fu_346 <= P_197;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd0))) begin
            P_56_fu_346 <= grp_fu_19351_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_57_fu_350 <= P_196;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd0))) begin
            P_57_fu_350 <= grp_fu_19355_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_58_fu_354 <= P_195;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd0))) begin
            P_58_fu_354 <= grp_fu_19359_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_59_fu_358 <= P_194;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd0))) begin
            P_59_fu_358 <= grp_fu_19363_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_60_fu_362 <= P_193;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd0))) begin
            P_60_fu_362 <= grp_fu_19367_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_61_fu_366 <= P_192;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd1))) begin
            P_61_fu_366 <= grp_fu_12431_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_62_fu_370 <= P_191;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd1))) begin
            P_62_fu_370 <= grp_fu_19351_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_63_fu_374 <= P_190;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd1))) begin
            P_63_fu_374 <= grp_fu_19355_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_64_fu_378 <= P_189;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd1))) begin
            P_64_fu_378 <= grp_fu_19359_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_65_fu_382 <= P_188;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd1))) begin
            P_65_fu_382 <= grp_fu_19363_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_66_fu_386 <= P_187;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd1))) begin
            P_66_fu_386 <= grp_fu_19367_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_67_fu_390 <= P_186;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd2))) begin
            P_67_fu_390 <= grp_fu_12431_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_68_fu_394 <= P_185;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd2))) begin
            P_68_fu_394 <= grp_fu_19351_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_69_fu_398 <= P_184;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd2))) begin
            P_69_fu_398 <= grp_fu_19355_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_70_fu_402 <= P_183;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd2))) begin
            P_70_fu_402 <= grp_fu_19359_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_71_fu_406 <= P_182;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd2))) begin
            P_71_fu_406 <= grp_fu_19363_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_72_fu_410 <= P_181;
        end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (i_12_reg_2285_pp0_iter9_reg == 3'd2))) begin
            P_72_fu_410 <= grp_fu_19367_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            P_fu_270 <= P_216;
        end else if ((1'b1 == ap_condition_1594)) begin
            P_fu_270 <= grp_fu_19367_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln117_fu_1380_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_266 <= add_ln117_fu_1386_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_266 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_12_reg_2285 <= ap_sig_allocacmp_i_12;
        i_12_reg_2285_pp0_iter1_reg <= i_12_reg_2285;
        icmp_ln117_reg_2295 <= icmp_ln117_fu_1380_p2;
        icmp_ln117_reg_2295_pp0_iter1_reg <= icmp_ln117_reg_2295;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        i_12_reg_2285_pp0_iter2_reg <= i_12_reg_2285_pp0_iter1_reg;
        i_12_reg_2285_pp0_iter3_reg <= i_12_reg_2285_pp0_iter2_reg;
        i_12_reg_2285_pp0_iter4_reg <= i_12_reg_2285_pp0_iter3_reg;
        i_12_reg_2285_pp0_iter5_reg <= i_12_reg_2285_pp0_iter4_reg;
        i_12_reg_2285_pp0_iter6_reg <= i_12_reg_2285_pp0_iter5_reg;
        i_12_reg_2285_pp0_iter7_reg <= i_12_reg_2285_pp0_iter6_reg;
        i_12_reg_2285_pp0_iter8_reg <= i_12_reg_2285_pp0_iter7_reg;
        i_12_reg_2285_pp0_iter9_reg <= i_12_reg_2285_pp0_iter8_reg;
        icmp_ln117_reg_2295_pp0_iter2_reg <= icmp_ln117_reg_2295_pp0_iter1_reg;
        icmp_ln117_reg_2295_pp0_iter3_reg <= icmp_ln117_reg_2295_pp0_iter2_reg;
        icmp_ln117_reg_2295_pp0_iter4_reg <= icmp_ln117_reg_2295_pp0_iter3_reg;
        icmp_ln117_reg_2295_pp0_iter5_reg <= icmp_ln117_reg_2295_pp0_iter4_reg;
        icmp_ln117_reg_2295_pp0_iter6_reg <= icmp_ln117_reg_2295_pp0_iter5_reg;
        icmp_ln117_reg_2295_pp0_iter7_reg <= icmp_ln117_reg_2295_pp0_iter6_reg;
        icmp_ln117_reg_2295_pp0_iter8_reg <= icmp_ln117_reg_2295_pp0_iter7_reg;
        mul102_i_reg_2304 <= grp_fu_12435_p_dout0;
        mul105_i_1_reg_2319 <= grp_fu_19375_p_dout0;
        mul105_i_2_reg_2324 <= grp_fu_19379_p_dout0;
        mul105_i_3_reg_2329 <= grp_fu_19383_p_dout0;
        mul105_i_4_reg_2334 <= grp_fu_19387_p_dout0;
        mul105_i_5_reg_2339 <= grp_fu_19347_p_dout0;
        mul105_i_reg_2314 <= grp_fu_19371_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln117_fu_1380_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_s_reg_2299 <= tmp_s_fu_1392_p8;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_283_out_ap_vld = 1'b1;
    end else begin
        P_283_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_284_out_ap_vld = 1'b1;
    end else begin
        P_284_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_285_out_ap_vld = 1'b1;
    end else begin
        P_285_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_286_out_ap_vld = 1'b1;
    end else begin
        P_286_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_287_out_ap_vld = 1'b1;
    end else begin
        P_287_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_288_out_ap_vld = 1'b1;
    end else begin
        P_288_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_289_out_ap_vld = 1'b1;
    end else begin
        P_289_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_290_out_ap_vld = 1'b1;
    end else begin
        P_290_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_291_out_ap_vld = 1'b1;
    end else begin
        P_291_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_292_out_ap_vld = 1'b1;
    end else begin
        P_292_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_293_out_ap_vld = 1'b1;
    end else begin
        P_293_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_294_out_ap_vld = 1'b1;
    end else begin
        P_294_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_295_out_ap_vld = 1'b1;
    end else begin
        P_295_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_296_out_ap_vld = 1'b1;
    end else begin
        P_296_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_297_out_ap_vld = 1'b1;
    end else begin
        P_297_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_298_out_ap_vld = 1'b1;
    end else begin
        P_298_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_299_out_ap_vld = 1'b1;
    end else begin
        P_299_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_300_out_ap_vld = 1'b1;
    end else begin
        P_300_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_301_out_ap_vld = 1'b1;
    end else begin
        P_301_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_302_out_ap_vld = 1'b1;
    end else begin
        P_302_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_303_out_ap_vld = 1'b1;
    end else begin
        P_303_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_304_out_ap_vld = 1'b1;
    end else begin
        P_304_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_305_out_ap_vld = 1'b1;
    end else begin
        P_305_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_306_out_ap_vld = 1'b1;
    end else begin
        P_306_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_307_out_ap_vld = 1'b1;
    end else begin
        P_307_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_308_out_ap_vld = 1'b1;
    end else begin
        P_308_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_309_out_ap_vld = 1'b1;
    end else begin
        P_309_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_310_out_ap_vld = 1'b1;
    end else begin
        P_310_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_311_out_ap_vld = 1'b1;
    end else begin
        P_311_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_312_out_ap_vld = 1'b1;
    end else begin
        P_312_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_313_out_ap_vld = 1'b1;
    end else begin
        P_313_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_314_out_ap_vld = 1'b1;
    end else begin
        P_314_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_315_out_ap_vld = 1'b1;
    end else begin
        P_315_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_316_out_ap_vld = 1'b1;
    end else begin
        P_316_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_317_out_ap_vld = 1'b1;
    end else begin
        P_317_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln117_reg_2295_pp0_iter8_reg == 1'd1))) begin
        P_318_out_ap_vld = 1'b1;
    end else begin
        P_318_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln117_fu_1380_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_12 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_12 = i_fu_266;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P_283_out = P_fu_270;

assign P_284_out = P_38_fu_274;

assign P_285_out = P_39_fu_278;

assign P_286_out = P_40_fu_282;

assign P_287_out = P_41_fu_286;

assign P_288_out = P_42_fu_290;

assign P_289_out = P_43_fu_294;

assign P_290_out = P_44_fu_298;

assign P_291_out = P_45_fu_302;

assign P_292_out = P_46_fu_306;

assign P_293_out = P_47_fu_310;

assign P_294_out = P_48_fu_314;

assign P_295_out = P_49_fu_318;

assign P_296_out = P_50_fu_322;

assign P_297_out = P_51_fu_326;

assign P_298_out = P_52_fu_330;

assign P_299_out = P_53_fu_334;

assign P_300_out = P_54_fu_338;

assign P_301_out = P_55_fu_342;

assign P_302_out = P_56_fu_346;

assign P_303_out = P_57_fu_350;

assign P_304_out = P_58_fu_354;

assign P_305_out = P_59_fu_358;

assign P_306_out = P_60_fu_362;

assign P_307_out = P_61_fu_366;

assign P_308_out = P_62_fu_370;

assign P_309_out = P_63_fu_374;

assign P_310_out = P_64_fu_378;

assign P_311_out = P_65_fu_382;

assign P_312_out = P_66_fu_386;

assign P_313_out = P_67_fu_390;

assign P_314_out = P_68_fu_394;

assign P_315_out = P_69_fu_398;

assign P_316_out = P_70_fu_402;

assign P_317_out = P_71_fu_406;

assign P_318_out = P_72_fu_410;

assign add_ln117_fu_1386_p2 = (ap_sig_allocacmp_i_12 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1594 = ((ap_enable_reg_pp0_iter10 == 1'b1) & ((i_12_reg_2285_pp0_iter9_reg == 3'd5) | ((i_12_reg_2285_pp0_iter9_reg == 3'd6) | (i_12_reg_2285_pp0_iter9_reg == 3'd7))));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_12431_p_ce = 1'b1;

assign grp_fu_12431_p_din0 = tmp_58_fu_1415_p8;

assign grp_fu_12431_p_din1 = mul105_i_reg_2314;

assign grp_fu_12431_p_opcode = 2'd0;

assign grp_fu_12435_p_ce = 1'b1;

assign grp_fu_12435_p_din0 = s_2;

assign grp_fu_12435_p_din1 = tmp_s_reg_2299;

assign grp_fu_19347_p_ce = 1'b1;

assign grp_fu_19347_p_din0 = mul102_i_reg_2304;

assign grp_fu_19347_p_din1 = K_5_reload;

assign grp_fu_19351_p_ce = 1'b1;

assign grp_fu_19351_p_din0 = tmp_108_1_fu_1427_p8;

assign grp_fu_19351_p_din1 = mul105_i_1_reg_2319;

assign grp_fu_19351_p_opcode = 2'd0;

assign grp_fu_19355_p_ce = 1'b1;

assign grp_fu_19355_p_din0 = tmp_108_2_fu_1439_p8;

assign grp_fu_19355_p_din1 = mul105_i_2_reg_2324;

assign grp_fu_19355_p_opcode = 2'd0;

assign grp_fu_19359_p_ce = 1'b1;

assign grp_fu_19359_p_din0 = tmp_108_3_fu_1451_p8;

assign grp_fu_19359_p_din1 = mul105_i_3_reg_2329;

assign grp_fu_19359_p_opcode = 2'd0;

assign grp_fu_19363_p_ce = 1'b1;

assign grp_fu_19363_p_din0 = tmp_108_4_fu_1463_p8;

assign grp_fu_19363_p_din1 = mul105_i_4_reg_2334;

assign grp_fu_19363_p_opcode = 2'd0;

assign grp_fu_19367_p_ce = 1'b1;

assign grp_fu_19367_p_din0 = tmp_108_5_fu_1475_p8;

assign grp_fu_19367_p_din1 = mul105_i_5_reg_2339;

assign grp_fu_19367_p_opcode = 2'd0;

assign grp_fu_19371_p_ce = 1'b1;

assign grp_fu_19371_p_din0 = mul102_i_reg_2304;

assign grp_fu_19371_p_din1 = K_reload;

assign grp_fu_19375_p_ce = 1'b1;

assign grp_fu_19375_p_din0 = mul102_i_reg_2304;

assign grp_fu_19375_p_din1 = K_1_reload;

assign grp_fu_19379_p_ce = 1'b1;

assign grp_fu_19379_p_din0 = mul102_i_reg_2304;

assign grp_fu_19379_p_din1 = K_2_reload;

assign grp_fu_19383_p_ce = 1'b1;

assign grp_fu_19383_p_din0 = mul102_i_reg_2304;

assign grp_fu_19383_p_din1 = K_3_reload;

assign grp_fu_19387_p_ce = 1'b1;

assign grp_fu_19387_p_din0 = mul102_i_reg_2304;

assign grp_fu_19387_p_din1 = K_4_reload;

assign icmp_ln117_fu_1380_p2 = ((ap_sig_allocacmp_i_12 == 3'd6) ? 1'b1 : 1'b0);

endmodule //ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_117_8
