-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_58_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    F_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_10_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_21_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_27_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    x_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_16_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_22_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_28_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    x_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_12_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_17_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_23_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_29_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    x_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_8_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_18_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_24_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_30_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    x_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_14_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_19_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_25_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_31_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    x_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_20_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_26_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    F_32_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    x_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    xp_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    xp_5_out_ap_vld : OUT STD_LOGIC;
    xp_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    xp_4_out_ap_vld : OUT STD_LOGIC;
    xp_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    xp_3_out_ap_vld : OUT STD_LOGIC;
    xp_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    xp_2_out_ap_vld : OUT STD_LOGIC;
    xp_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    xp_1_out_ap_vld : OUT STD_LOGIC;
    xp_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    xp_out_ap_vld : OUT STD_LOGIC;
    grp_fu_19343_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_19343_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_19343_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_19343_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_19343_p_ce : OUT STD_LOGIC;
    grp_fu_19347_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_19347_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_19347_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_19347_p_ce : OUT STD_LOGIC );
end;


architecture behav of ekf_batch_ekf_batch_Pipeline_VITIS_LOOP_58_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv32_3DCCCCCD : STD_LOGIC_VECTOR (31 downto 0) := "00111101110011001100110011001101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln58_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_4_reg_844 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter11_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter12_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter13_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter14_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter15_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter16_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter17_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter18_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter19_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter20_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter21_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter22_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter23_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter24_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter25_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal i_4_reg_844_pp0_iter26_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln58_reg_853 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_reg_853_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_501_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_857 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_reg_862 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_524_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_867 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_reg_872 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_461_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_1_reg_877 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_535_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_882 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_437_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_reg_887 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_465_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_2_reg_892 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_546_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_reg_897 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_441_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_reg_902 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_469_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_3_reg_907 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_558_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_reg_912 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_445_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_reg_917 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_473_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_4_reg_922 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_570_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_927 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_449_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_4_reg_932 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_477_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_5_reg_937 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_128 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln58_fu_495_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal xp_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_453_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xp_1_fu_136 : STD_LOGIC_VECTOR (31 downto 0);
    signal xp_2_fu_140 : STD_LOGIC_VECTOR (31 downto 0);
    signal xp_3_fu_144 : STD_LOGIC_VECTOR (31 downto 0);
    signal xp_4_fu_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal xp_5_fu_152 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ekf_batch_faddfsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ekf_batch_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ekf_batch_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ekf_batch_mux_6_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ekf_batch_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fadd_32ns_32ns_32_4_full_dsp_1_U117 : component ekf_batch_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_reg_872,
        din1 => mul_i_1_reg_877,
        ce => ap_const_logic_1,
        dout => grp_fu_437_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U118 : component ekf_batch_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_1_reg_887,
        din1 => mul_i_2_reg_892,
        ce => ap_const_logic_1,
        dout => grp_fu_441_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U119 : component ekf_batch_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_2_reg_902,
        din1 => mul_i_3_reg_907,
        ce => ap_const_logic_1,
        dout => grp_fu_445_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U120 : component ekf_batch_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_3_reg_917,
        din1 => mul_i_4_reg_922,
        ce => ap_const_logic_1,
        dout => grp_fu_449_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U121 : component ekf_batch_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_4_reg_932,
        din1 => mul_i_5_reg_937,
        ce => ap_const_logic_1,
        dout => grp_fu_453_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U123 : component ekf_batch_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_1_reg_867,
        din1 => x_1_reload,
        ce => ap_const_logic_1,
        dout => grp_fu_461_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U124 : component ekf_batch_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_2_reg_882,
        din1 => x_2_reload,
        ce => ap_const_logic_1,
        dout => grp_fu_465_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U125 : component ekf_batch_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_3_reg_897,
        din1 => x_3_reload,
        ce => ap_const_logic_1,
        dout => grp_fu_469_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U126 : component ekf_batch_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_4_reg_912,
        din1 => x_4_reload,
        ce => ap_const_logic_1,
        dout => grp_fu_473_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U127 : component ekf_batch_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_5_reg_927,
        din1 => x_5_reload,
        ce => ap_const_logic_1,
        dout => grp_fu_477_p2);

    mux_6_3_32_1_1_U128 : component ekf_batch_mux_6_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => F_reload,
        din1 => F_5_reload,
        din2 => F_10_reload,
        din3 => F_15_reload,
        din4 => F_21_reload,
        din5 => F_27_reload,
        din6 => ap_sig_allocacmp_i_4,
        dout => tmp_fu_501_p8);

    mux_6_3_32_1_1_U129 : component ekf_batch_mux_6_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => F_1_reload,
        din1 => F_6_reload,
        din2 => F_11_reload,
        din3 => F_16_reload,
        din4 => F_22_reload,
        din5 => F_28_reload,
        din6 => i_4_reg_844_pp0_iter3_reg,
        dout => tmp_1_fu_524_p8);

    mux_6_3_32_1_1_U130 : component ekf_batch_mux_6_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => F_2_reload,
        din1 => F_7_reload,
        din2 => F_12_reload,
        din3 => F_17_reload,
        din4 => F_23_reload,
        din5 => F_29_reload,
        din6 => i_4_reg_844_pp0_iter7_reg,
        dout => tmp_2_fu_535_p8);

    mux_6_3_32_1_1_U131 : component ekf_batch_mux_6_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_3DCCCCCD,
        din1 => F_8_reload,
        din2 => F_13_reload,
        din3 => F_18_reload,
        din4 => F_24_reload,
        din5 => F_30_reload,
        din6 => i_4_reg_844_pp0_iter11_reg,
        dout => tmp_3_fu_546_p8);

    mux_6_3_32_1_1_U132 : component ekf_batch_mux_6_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => F_3_reload,
        din1 => ap_const_lv32_3DCCCCCD,
        din2 => F_14_reload,
        din3 => F_19_reload,
        din4 => F_25_reload,
        din5 => F_31_reload,
        din6 => i_4_reg_844_pp0_iter15_reg,
        dout => tmp_4_fu_558_p8);

    mux_6_3_32_1_1_U133 : component ekf_batch_mux_6_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => F_4_reload,
        din1 => F_9_reload,
        din2 => ap_const_lv32_3DCCCCCD,
        din3 => F_20_reload,
        din4 => F_26_reload,
        din5 => F_32_reload,
        din6 => i_4_reg_844_pp0_iter19_reg,
        dout => tmp_5_fu_570_p8);

    flow_control_loop_pipe_sequential_init_U : component ekf_batch_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter26_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln58_fu_489_p2 = ap_const_lv1_0))) then 
                    i_fu_128 <= add_ln58_fu_495_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_128 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                acc_1_reg_887 <= grp_fu_437_p2;
                acc_2_reg_902 <= grp_fu_441_p2;
                acc_3_reg_917 <= grp_fu_445_p2;
                acc_4_reg_932 <= grp_fu_449_p2;
                acc_reg_872 <= grp_fu_19343_p_dout0;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                i_4_reg_844_pp0_iter10_reg <= i_4_reg_844_pp0_iter9_reg;
                i_4_reg_844_pp0_iter11_reg <= i_4_reg_844_pp0_iter10_reg;
                i_4_reg_844_pp0_iter12_reg <= i_4_reg_844_pp0_iter11_reg;
                i_4_reg_844_pp0_iter13_reg <= i_4_reg_844_pp0_iter12_reg;
                i_4_reg_844_pp0_iter14_reg <= i_4_reg_844_pp0_iter13_reg;
                i_4_reg_844_pp0_iter15_reg <= i_4_reg_844_pp0_iter14_reg;
                i_4_reg_844_pp0_iter16_reg <= i_4_reg_844_pp0_iter15_reg;
                i_4_reg_844_pp0_iter17_reg <= i_4_reg_844_pp0_iter16_reg;
                i_4_reg_844_pp0_iter18_reg <= i_4_reg_844_pp0_iter17_reg;
                i_4_reg_844_pp0_iter19_reg <= i_4_reg_844_pp0_iter18_reg;
                i_4_reg_844_pp0_iter20_reg <= i_4_reg_844_pp0_iter19_reg;
                i_4_reg_844_pp0_iter21_reg <= i_4_reg_844_pp0_iter20_reg;
                i_4_reg_844_pp0_iter22_reg <= i_4_reg_844_pp0_iter21_reg;
                i_4_reg_844_pp0_iter23_reg <= i_4_reg_844_pp0_iter22_reg;
                i_4_reg_844_pp0_iter24_reg <= i_4_reg_844_pp0_iter23_reg;
                i_4_reg_844_pp0_iter25_reg <= i_4_reg_844_pp0_iter24_reg;
                i_4_reg_844_pp0_iter26_reg <= i_4_reg_844_pp0_iter25_reg;
                i_4_reg_844_pp0_iter2_reg <= i_4_reg_844_pp0_iter1_reg;
                i_4_reg_844_pp0_iter3_reg <= i_4_reg_844_pp0_iter2_reg;
                i_4_reg_844_pp0_iter4_reg <= i_4_reg_844_pp0_iter3_reg;
                i_4_reg_844_pp0_iter5_reg <= i_4_reg_844_pp0_iter4_reg;
                i_4_reg_844_pp0_iter6_reg <= i_4_reg_844_pp0_iter5_reg;
                i_4_reg_844_pp0_iter7_reg <= i_4_reg_844_pp0_iter6_reg;
                i_4_reg_844_pp0_iter8_reg <= i_4_reg_844_pp0_iter7_reg;
                i_4_reg_844_pp0_iter9_reg <= i_4_reg_844_pp0_iter8_reg;
                icmp_ln58_reg_853_pp0_iter10_reg <= icmp_ln58_reg_853_pp0_iter9_reg;
                icmp_ln58_reg_853_pp0_iter11_reg <= icmp_ln58_reg_853_pp0_iter10_reg;
                icmp_ln58_reg_853_pp0_iter12_reg <= icmp_ln58_reg_853_pp0_iter11_reg;
                icmp_ln58_reg_853_pp0_iter13_reg <= icmp_ln58_reg_853_pp0_iter12_reg;
                icmp_ln58_reg_853_pp0_iter14_reg <= icmp_ln58_reg_853_pp0_iter13_reg;
                icmp_ln58_reg_853_pp0_iter15_reg <= icmp_ln58_reg_853_pp0_iter14_reg;
                icmp_ln58_reg_853_pp0_iter16_reg <= icmp_ln58_reg_853_pp0_iter15_reg;
                icmp_ln58_reg_853_pp0_iter17_reg <= icmp_ln58_reg_853_pp0_iter16_reg;
                icmp_ln58_reg_853_pp0_iter18_reg <= icmp_ln58_reg_853_pp0_iter17_reg;
                icmp_ln58_reg_853_pp0_iter19_reg <= icmp_ln58_reg_853_pp0_iter18_reg;
                icmp_ln58_reg_853_pp0_iter20_reg <= icmp_ln58_reg_853_pp0_iter19_reg;
                icmp_ln58_reg_853_pp0_iter21_reg <= icmp_ln58_reg_853_pp0_iter20_reg;
                icmp_ln58_reg_853_pp0_iter22_reg <= icmp_ln58_reg_853_pp0_iter21_reg;
                icmp_ln58_reg_853_pp0_iter23_reg <= icmp_ln58_reg_853_pp0_iter22_reg;
                icmp_ln58_reg_853_pp0_iter24_reg <= icmp_ln58_reg_853_pp0_iter23_reg;
                icmp_ln58_reg_853_pp0_iter25_reg <= icmp_ln58_reg_853_pp0_iter24_reg;
                icmp_ln58_reg_853_pp0_iter2_reg <= icmp_ln58_reg_853_pp0_iter1_reg;
                icmp_ln58_reg_853_pp0_iter3_reg <= icmp_ln58_reg_853_pp0_iter2_reg;
                icmp_ln58_reg_853_pp0_iter4_reg <= icmp_ln58_reg_853_pp0_iter3_reg;
                icmp_ln58_reg_853_pp0_iter5_reg <= icmp_ln58_reg_853_pp0_iter4_reg;
                icmp_ln58_reg_853_pp0_iter6_reg <= icmp_ln58_reg_853_pp0_iter5_reg;
                icmp_ln58_reg_853_pp0_iter7_reg <= icmp_ln58_reg_853_pp0_iter6_reg;
                icmp_ln58_reg_853_pp0_iter8_reg <= icmp_ln58_reg_853_pp0_iter7_reg;
                icmp_ln58_reg_853_pp0_iter9_reg <= icmp_ln58_reg_853_pp0_iter8_reg;
                mul_i_1_reg_877 <= grp_fu_461_p2;
                mul_i_2_reg_892 <= grp_fu_465_p2;
                mul_i_3_reg_907 <= grp_fu_469_p2;
                mul_i_4_reg_922 <= grp_fu_473_p2;
                mul_i_5_reg_937 <= grp_fu_477_p2;
                mul_i_reg_862 <= grp_fu_19347_p_dout0;
                tmp_1_reg_867 <= tmp_1_fu_524_p8;
                tmp_2_reg_882 <= tmp_2_fu_535_p8;
                tmp_3_reg_897 <= tmp_3_fu_546_p8;
                tmp_4_reg_912 <= tmp_4_fu_558_p8;
                tmp_5_reg_927 <= tmp_5_fu_570_p8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_4_reg_844 <= ap_sig_allocacmp_i_4;
                i_4_reg_844_pp0_iter1_reg <= i_4_reg_844;
                icmp_ln58_reg_853 <= icmp_ln58_fu_489_p2;
                icmp_ln58_reg_853_pp0_iter1_reg <= icmp_ln58_reg_853;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln58_fu_489_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_857 <= tmp_fu_501_p8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((i_4_reg_844_pp0_iter26_reg = ap_const_lv3_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then
                xp_1_fu_136 <= grp_fu_453_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((i_4_reg_844_pp0_iter26_reg = ap_const_lv3_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then
                xp_2_fu_140 <= grp_fu_453_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((i_4_reg_844_pp0_iter26_reg = ap_const_lv3_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then
                xp_3_fu_144 <= grp_fu_453_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((i_4_reg_844_pp0_iter26_reg = ap_const_lv3_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then
                xp_4_fu_148 <= grp_fu_453_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1) and ((i_4_reg_844_pp0_iter26_reg = ap_const_lv3_5) or ((i_4_reg_844_pp0_iter26_reg = ap_const_lv3_6) or (i_4_reg_844_pp0_iter26_reg = ap_const_lv3_7))))) then
                xp_5_fu_152 <= grp_fu_453_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((i_4_reg_844_pp0_iter26_reg = ap_const_lv3_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then
                xp_fu_132 <= grp_fu_453_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_fu_495_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln58_fu_489_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln58_fu_489_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter26_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter26_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_128, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_128;
        end if; 
    end process;

    grp_fu_19343_p_ce <= ap_const_logic_1;
    grp_fu_19343_p_din0 <= mul_i_reg_862;
    grp_fu_19343_p_din1 <= ap_const_lv32_0;
    grp_fu_19343_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_19347_p_ce <= ap_const_logic_1;
    grp_fu_19347_p_din0 <= tmp_reg_857;
    grp_fu_19347_p_din1 <= x_reload;
    icmp_ln58_fu_489_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv3_6) else "0";
    xp_1_out <= xp_1_fu_136;

    xp_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln58_reg_853_pp0_iter25_reg)
    begin
        if (((icmp_ln58_reg_853_pp0_iter25_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            xp_1_out_ap_vld <= ap_const_logic_1;
        else 
            xp_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xp_2_out <= xp_2_fu_140;

    xp_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln58_reg_853_pp0_iter25_reg)
    begin
        if (((icmp_ln58_reg_853_pp0_iter25_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            xp_2_out_ap_vld <= ap_const_logic_1;
        else 
            xp_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xp_3_out <= xp_3_fu_144;

    xp_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln58_reg_853_pp0_iter25_reg)
    begin
        if (((icmp_ln58_reg_853_pp0_iter25_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            xp_3_out_ap_vld <= ap_const_logic_1;
        else 
            xp_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xp_4_out <= xp_4_fu_148;

    xp_4_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln58_reg_853_pp0_iter25_reg)
    begin
        if (((icmp_ln58_reg_853_pp0_iter25_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            xp_4_out_ap_vld <= ap_const_logic_1;
        else 
            xp_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xp_5_out <= xp_5_fu_152;

    xp_5_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln58_reg_853_pp0_iter25_reg)
    begin
        if (((icmp_ln58_reg_853_pp0_iter25_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            xp_5_out_ap_vld <= ap_const_logic_1;
        else 
            xp_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xp_out <= xp_fu_132;

    xp_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln58_reg_853_pp0_iter25_reg)
    begin
        if (((icmp_ln58_reg_853_pp0_iter25_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            xp_out_ap_vld <= ap_const_logic_1;
        else 
            xp_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
